console.log("run typescript");
import * as StaticFactoryMethod from "./creational/StaticFactoryMethod";
StaticFactoryMethod.test();
import * as FactoryMethod from "./creational/FactoryMethod";
FactoryMethod.test();
import * as AbstractFactory from "./creational/AbstractFactory";
AbstractFactory.test();
import * as Builder from "./creational/Builder";
Builder.test();
import * as Singleton from "./creational/Singleton";
Singleton.test();
